// Publication list. Citation counts are taken from Google Scholar
// (https://scholar.google.com/citations?user=_cDpLFAAAAAJ) — update them there first.

export type Pub = {
  title: string
  authors: string
  venue: string
  year: number
  doi: string
  impact: string
  tags: string[]
  citations?: number
  featured?: boolean
  type: 'journal' | 'conference'
}

export const publications: Pub[] = [
  {
    title: 'DMSPC: A novel approach for meta learner selection in stacked ensemble to enhance speech emotion recognition',
    authors: 'Tripathi A., Rani P.',
    venue: 'International Journal of Computers and Applications (Taylor & Francis)',
    year: 2026,
    doi: '',
    impact: 'Journal',
    tags: ['Speech Emotion Recognition', 'Ensemble Learning'],
    type: 'journal',
  },
  {
    title: 'CAHNetF-DTP: A Community-Aware Heterogeneous Network-Based Embedding Framework for Drug-Target Interaction Prediction',
    authors: 'Mittal A., Rani P., Jain A.',
    venue: 'Journal of Chemical Information and Modeling (ACS), 66(10), 5661–5679',
    year: 2026,
    doi: '',
    impact: 'SCIE',
    tags: ['Drug Discovery', 'Graph Embedding', 'Deep Learning'],
    featured: true,
    type: 'journal',
  },
  {
    title: 'Multilingual speech emotion recognition using IGRFXG – Ensemble feature selection approach',
    authors: 'Tripathi A., Rani P.',
    venue: 'Applied Acoustics (Elsevier), Vol. 240',
    year: 2025,
    doi: '',
    impact: 'SCIE',
    tags: ['Speech Emotion Recognition', 'Feature Selection', 'Machine Learning'],
    citations: 4,
    featured: true,
    type: 'journal',
  },
  {
    title: 'QEKLR: Quantum-enhanced kernel logistic regression for classification',
    authors: 'Misra S., Rani P.',
    venue: 'The Journal of Supercomputing (Springer), Vol. 81',
    year: 2025,
    doi: 'https://doi.org/10.1007/s11227-025-07266-y',
    impact: 'SCIE',
    tags: ['Quantum Computing', 'Quantum Machine Learning'],
    citations: 6,
    featured: true,
    type: 'journal',
  },
  {
    title: 'QuMLF: A Quantum-based Framework for Heart Disease Prediction Using QSVC and Genetic Algorithm',
    authors: 'Misra S., Rani P.',
    venue: 'Proc. 5th International Conference on Advances in Computer Science',
    year: 2025,
    doi: '',
    impact: '',
    tags: ['Quantum Computing', 'Healthcare', 'Genetic Algorithm'],
    type: 'conference',
  },
  {
    title: 'Evaluating the Efficiency and Fidelity of Image Compression Methods: From Classical Codecs to Deep Learning Approaches',
    authors: 'Rani P., Gupta R., Raj M., Tanwar K., Dahiya T.',
    venue: '2nd International Conference on Pioneering Developments in Computer Science',
    year: 2025,
    doi: '',
    impact: '',
    tags: ['Image Compression', 'Deep Learning'],
    type: 'conference',
  },
  {
    title: 'HyperAttentionDTI: Bi-Directional Cross-Attention for Enhanced Drug-Target Interaction Prediction',
    authors: 'Rani P., Arora K., Garg A., Johri S., Dahiya T.',
    venue: '2nd International Conference on Pioneering Developments in Computer Science',
    year: 2025,
    doi: '',
    impact: '',
    tags: ['Drug Discovery', 'Attention', 'Deep Learning'],
    type: 'conference',
  },
  {
    title: 'Deep Learning-Based Multi-Class Classification of Brain MRI for Early Detection of Alzheimer\'s Disease and Cognitive Impairment',
    authors: 'Rani P., Dahiya T., Rawat V., Sinha R., Meena J., Kumar N.',
    venue: '2nd International Conference on Pioneering Developments in Computer Science',
    year: 2025,
    doi: '',
    impact: '',
    tags: ['Healthcare', 'Alzheimer\'s', 'Deep Learning'],
    type: 'conference',
  },
  {
    title: 'Deep Learning-Based Skin Cancer Detection: A Comprehensive Approach for Automated Dermatological Diagnosis',
    authors: 'Rani P., Dahiya T., Gupta D., Yadav P., Sachdeva T.',
    venue: '2nd International Conference on Pioneering Developments in Computer Science',
    year: 2025,
    doi: '',
    impact: '',
    tags: ['Healthcare', 'Deep Learning', 'Medical Imaging'],
    citations: 1,
    type: 'conference',
  },
  {
    title: 'SlideBERT-DTI: An improved framework using Deep learning-based approach for Drug-Target interaction prediction',
    authors: 'Mittal A., Rani P., Jain A.',
    venue: '2nd Global AI Summit – International Conference on Artificial Intelligence',
    year: 2025,
    doi: '',
    impact: '',
    tags: ['Drug Discovery', 'Transformers', 'Deep Learning'],
    type: 'conference',
  },
  {
    title: 'FNNet: A secure ensemble-based approach for fake news detection using blockchain',
    authors: 'Rani P., Shokeen J.',
    venue: 'The Journal of Supercomputing (Springer), Vol. 80',
    year: 2024,
    doi: 'https://doi.org/10.1007/s11227-024-06216-4',
    impact: 'SCIE',
    tags: ['Blockchain', 'Fake News', 'Ensemble Learning'],
    citations: 28,
    featured: true,
    type: 'journal',
  },
  {
    title: 'An Improved MSER using Grid Search based PCA and Ensemble Voting Technique',
    authors: 'Tripathi A., Rani P.',
    venue: 'Multimedia Tools and Applications (Springer)',
    year: 2024,
    doi: '',
    impact: 'SCIE',
    tags: ['Speech Emotion Recognition', 'PCA', 'Ensemble Learning'],
    citations: 14,
    type: 'journal',
  },
  {
    title: 'Quantum Machine Learning: A Comprehensive Overview and Analysis',
    authors: 'Misra S., Rani P.',
    venue: '15th International Conference on Computing Communication and Networking Technologies (ICCCNT)',
    year: 2024,
    doi: '',
    impact: 'IEEE',
    tags: ['Quantum Computing', 'Quantum Machine Learning', 'Survey'],
    citations: 7,
    type: 'conference',
  },
  {
    title: 'A pseudo-labelled ensemble inference for fast and efficient real field photovoltaic system\'s power prediction',
    authors: 'Dhingra B., Tyagi S., Verma A., Tomar A., Rani P.',
    venue: 'Optik (Elsevier), Vol. 287, 171095',
    year: 2023,
    doi: '',
    impact: 'SCIE',
    tags: ['Ensemble Learning', 'Energy', 'Prediction'],
    citations: 4,
    type: 'journal',
  },
  {
    title: 'An Application-Oriented Review of Blockchain-Based Recommender Systems',
    authors: 'Rani P., Tewari T.',
    venue: 'International Conference on Innovative Computing and Communications (ICICC), Springer',
    year: 2023,
    doi: '',
    impact: 'Springer',
    tags: ['Blockchain', 'Recommender Systems', 'Review'],
    citations: 1,
    type: 'conference',
  },
  {
    title: 'Text-to-Image Synthesis using BERT Embeddings and Multi-Stage GAN',
    authors: 'Rani P. et al.',
    venue: 'International Conference on Innovative Computing and Communications (ICICC), Springer',
    year: 2023,
    doi: '',
    impact: 'Springer',
    tags: ['Generative AI', 'GAN', 'NLP'],
    citations: 1,
    type: 'conference',
  },
  {
    title: 'PCA-Based Feature Selection and Hybrid Classification Model for Speech Emotion Recognition',
    authors: 'Tripathi A., Rani P.',
    venue: 'International Conference on Innovative Computing and Communications (ICICC), Springer',
    year: 2023,
    doi: '',
    impact: 'Springer',
    tags: ['Speech Emotion Recognition', 'PCA', 'Machine Learning'],
    citations: 7,
    type: 'conference',
  },
  {
    title: 'Comparison between PCA and GA for Emotion Recognition from Speech',
    authors: 'Rani P., Tripathi A. et al.',
    venue: 'International Conference on Innovative Computing and Communications (ICICC), Springer',
    year: 2023,
    doi: '',
    impact: 'Springer',
    tags: ['Speech Emotion Recognition', 'Genetic Algorithm', 'PCA'],
    type: 'conference',
  },
  {
    title: 'Vehicular Ad Hoc Network: A Review',
    authors: 'Monika, Rani P.',
    venue: 'International Conference on Innovative Computing and Communications (ICICC), Springer, pp. 243–252',
    year: 2023,
    doi: '',
    impact: 'Springer',
    tags: ['IoT', 'VANET', 'Review'],
    type: 'conference',
  },
  {
    title: 'Multilingual Emotion Analysis from Speech',
    authors: 'Rani P., Tripathi A., Shoaib M., Yadav S., Yadav M.',
    venue: 'International Conference on Innovative Computing and Communications (ICICC), Springer',
    year: 2022,
    doi: '',
    impact: 'Springer',
    tags: ['Speech Emotion Recognition', 'Multilingual'],
    type: 'conference',
  },
  {
    title: 'A Comparative Survey of Consensus Algorithms Based on Proof of Work',
    authors: 'Rani P., Bhambay R.',
    venue: 'Emerging Technologies in Data Mining and Information Security (Springer LNNS)',
    year: 2022,
    doi: '',
    impact: 'Springer',
    tags: ['Blockchain', 'Consensus', 'Survey'],
    citations: 15,
    type: 'conference',
  },
  {
    title: 'Designing an LSTM and Genetic Algorithm-based Sentiment Analysis Model for COVID-19',
    authors: 'Rani P., Shokeen J., Majithia A., Agarwal A., Bhatghare A., Malhotra J.',
    venue: 'Data Analytics and Management (ICDAM 2021), Springer',
    year: 2022,
    doi: '',
    impact: 'Springer',
    tags: ['LSTM', 'Sentiment Analysis', 'COVID-19'],
    citations: 8,
    type: 'conference',
  },
  {
    title: 'Sociocentric SNA on Fuzzy Graph Social Network Model',
    authors: 'Rani P., Tayal D., Bhatia M.P.S.',
    venue: 'Soft Computing (Springer Nature)',
    year: 2022,
    doi: 'http://doi.org/10.1007/s00500-022-06961-9',
    impact: 'SCIE · IF 3.732',
    tags: ['Social Networks', 'Fuzzy Logic'],
    type: 'journal',
  },
  {
    title: 'Blockchain-based rumor detection approach for COVID-19',
    authors: 'Rani P., Jain V., Shokeen J., Balyan A.',
    venue: 'Journal of Ambient Intelligence and Humanized Computing (Springer)',
    year: 2022,
    doi: 'https://doi.org/10.1007/s12652-022-03900-2',
    impact: 'SCIE · IF 3.662',
    tags: ['Blockchain', 'COVID-19', 'AI'],
    citations: 32,
    type: 'journal',
  },
  {
    title: 'Blockchain-based IoT enabled health monitoring system',
    authors: 'Rani P., Preeti K., Jain V., Shokeen J., Sweety',
    venue: 'The Journal of Supercomputing (Springer)',
    year: 2022,
    doi: 'https://doi.org/10.1007/s11227-022-04584-3',
    impact: 'SCIE · IF 2.557',
    tags: ['Blockchain', 'IoT', 'Healthcare'],
    citations: 35,
    featured: true,
    type: 'journal',
  },
  {
    title: 'An Enhanced Crow Search Inspired Feature Selection Technique for Intrusion Detection Based Wireless Network System',
    authors: 'Khanna A., Rani P., Garg P., Singh P.K., Khamparia A.',
    venue: 'Wireless Personal Communications (Springer)',
    year: 2022,
    doi: 'https://doi.org/10.1007/s11277-021-08766-9',
    impact: 'SCIE · IF 2.017',
    tags: ['Intrusion Detection', 'Feature Selection', 'Wireless'],
    citations: 56,
    type: 'journal',
  },
  {
    title: 'Stock Price Prediction Using Reinforcement Learning',
    authors: 'Rani P., Shokeen J., Singh A., Singh A., Kumar S., Raghuvanshi N.',
    venue: 'Int. Conference on Innovative Computing and Communications, Springer',
    year: 2022,
    doi: 'https://doi.org/10.1007/978-981-16-2597-8_6',
    impact: 'Springer AISC',
    tags: ['Reinforcement Learning', 'Stock Prediction', 'AI'],
    citations: 7,
    type: 'conference',
  },
  {
    title: 'Improving Accuracy of Deep Learning-Based Compression by Introducing Perceptual Loss in Industrial IoT',
    authors: 'Rani P., Jain V., Saif M., Mugloo S.H., Hirna M., Jain S.',
    venue: 'Int. Conference on Innovative Computing and Communications, Springer',
    year: 2022,
    doi: 'https://doi.org/10.1007/978-981-16-3071-2_6',
    impact: 'Springer AISC',
    tags: ['Deep Learning', 'IIoT', 'Compression'],
    citations: 4,
    type: 'conference',
  },
  {
    title: 'Smart Home Automation: Literature Review',
    authors: 'Rani P., Sharma P., Jain V.',
    venue: 'International Conference on Innovative Computing and Communications (ICICC), Springer',
    year: 2021,
    doi: '',
    impact: 'Springer',
    tags: ['IoT', 'Smart Home', 'Review'],
    citations: 2,
    type: 'conference',
  },
  {
    title: 'A survey of tools for social network analysis',
    authors: 'Rani P., Shokeen J.',
    venue: 'Int. J. Web Engineering and Technology (Inderscience)',
    year: 2021,
    doi: 'https://dx.doi.org/10.1504/IJWET.2021.119879',
    impact: 'Scopus',
    tags: ['SNA', 'Survey', 'Tools'],
    citations: 34,
    type: 'journal',
  },
  {
    title: 'Conical SNA using Fuzzy K-Medoids based on user experience',
    authors: 'Rani P., Bhatia M.P.S., Tayal D.K.',
    venue: 'Int. J. of Electrical Engineering and Education',
    year: 2021,
    doi: '10.1177/0020720920988490',
    impact: 'Scopus',
    tags: ['SNA', 'Fuzzy Logic', 'K-Medoids'],
    citations: 4,
    type: 'journal',
  },
  {
    title: 'Blockchain-Based Security Enhancement and Spectrum Sensing in Cognitive Radio Network',
    authors: 'Khanna A., Rani P., Tariq H.S., Gupta D., Kansal V., Rodrigues J.J.P.C.',
    venue: 'Wireless Personal Communications (Springer)',
    year: 2021,
    doi: 'https://doi.org/10.1007/s11277-021-08729-0',
    impact: 'SCIE · IF 2.017',
    tags: ['Blockchain', 'Cognitive Radio', 'Security'],
    citations: 47,
    type: 'journal',
  },
  {
    title: 'Optimal deep learning approaches and healthcare big data analytics for mobile networks toward 5G',
    authors: 'Pustokhin D., Pustokin I., Rani P. et al.',
    venue: 'Computers & Electrical Engineering (Elsevier)',
    year: 2021,
    doi: 'https://doi.org/10.1016/j.compeleceng.2021.107376',
    impact: 'SCIE · IF 4.152',
    tags: ['Deep Learning', 'Healthcare', '5G'],
    citations: 41,
    type: 'journal',
  },
  {
    title: 'An Adaptive Neuro Fuzzy Modelling and Prediction System for Diagnosis of COVID-19',
    authors: 'Khamparia A., Jain R., Rani P., Gupta D., Khanna A.',
    venue: 'Applied and Computational Mathematics',
    year: 2021,
    doi: '',
    impact: 'SCIE · IF 3.898',
    tags: ['Neuro-Fuzzy', 'COVID-19', 'Diagnosis'],
    citations: 5,
    type: 'journal',
  },
  {
    title: 'An Internet of Health Things-driven Deep Learning Framework for Detection and Classification of Skin Cancer using Transfer Learning',
    authors: 'Khamparia A., Singh P.K., Rani P., Samanta D., Khanna A., Bhushan B.',
    venue: 'Transactions on Emerging Telecommunications Technologies',
    year: 2021,
    doi: '10.1002/ett.3963',
    impact: 'SCIE · IF 3.310',
    tags: ['Deep Learning', 'Healthcare', 'Transfer Learning'],
    citations: 264,
    featured: true,
    type: 'journal',
  },
  {
    title: 'Heterogeneous load balancing clustering protocol for Wireless Sensor Networks',
    authors: 'Kaur S., Naaz R., Khamparia A., Rani P., Gupta D.',
    venue: 'Cognitive Systems Research (Elsevier)',
    year: 2021,
    doi: 'https://doi.org/10.1016/j.cogsys.2021.07.00',
    impact: 'SCIE · IF 4.541',
    tags: ['WSN', 'Load Balancing', 'Clustering'],
    citations: 20,
    type: 'journal',
  },
  {
    title: 'Optimal deep learning based image compression technique for data transmission on IIoT',
    authors: 'Sujitha B., Parvathy V.S., Lydia E.L., Rani P., Polkowski Z., Shankar K.',
    venue: 'Transactions on Emerging Telecommunications Technologies',
    year: 2021,
    doi: 'https://doi.org/10.1002/ett.3976',
    impact: 'SCIE · IF 3.310',
    tags: ['Deep Learning', 'IIoT', 'Compression'],
    citations: 112,
    type: 'journal',
  },
  {
    title: 'Credit Card Fraud Detection Using Blockchain and Simulated Annealing k-Means Algorithm',
    authors: 'Rani P., Shokeen J., Agarwal A., Bhatghare A., Majithia A., Malhotra J.',
    venue: 'Int. Conference on Innovative Computing and Communications, Springer',
    year: 2021,
    doi: 'https://doi.org/10.1007/978-981-16-3071-2_5',
    impact: 'Springer AISC',
    tags: ['Blockchain', 'Fraud Detection', 'K-Means'],
    citations: 11,
    type: 'conference',
  },
  {
    title: 'A Secured Supply Chain Network for Route Optimization and Product Traceability using Blockchain in IoT',
    authors: 'Rani P., Jain V., Joshi M., Khandelwal M.',
    venue: 'Int. Conference on Data Analytics and Management',
    year: 2021,
    doi: '',
    impact: 'Conference',
    tags: ['Supply Chain', 'Blockchain', 'IoT'],
    citations: 15,
    type: 'conference',
  },
  {
    title: 'A Secure Epidemic Routing using Blockchain in Opportunistic Internet of Things',
    authors: 'Rani P., Singh P.P., Balyan A., Shokeen J., Jain V.',
    venue: 'Int. Conference on Data Analytics and Management',
    year: 2021,
    doi: '',
    impact: 'Conference',
    tags: ['Blockchain', 'IoT', 'Epidemic Routing'],
    citations: 16,
    type: 'conference',
  },
  {
    title: 'A trust-based approach to extract social relationships for recommendation',
    authors: 'Shokeen J., Rana C., Rani P.',
    venue: 'Int. Conference on Data Analytics and Management',
    year: 2021,
    doi: '',
    impact: 'Conference',
    tags: ['Trust', 'Social Networks', 'Recommendation'],
    citations: 11,
    type: 'conference',
  },
  {
    title: 'A New Dimensionality Reduction technique for K-Means Clustering performance Improvement',
    authors: 'Rani P., Madan N.',
    venue: 'Mukt Shabd Journal',
    year: 2020,
    doi: '09.0014.MSJ.2020.V9I5.0086781.10357',
    impact: 'UGC Care',
    tags: ['K-Means', 'Dimensionality Reduction', 'Clustering'],
    type: 'journal',
  },
  {
    title: 'A Probabilistic Routing-based Secure Approach for Opportunistic IoT Network using Blockchain',
    authors: 'Rani P., Balyan A., Jain V., Sangwan D., Pal P., Shokeen J.',
    venue: '17th India Council International Conference (INDICON), IEEE',
    year: 2020,
    doi: '',
    impact: 'IEEE Xplore',
    tags: ['IoT', 'Blockchain', 'Routing'],
    citations: 13,
    type: 'conference',
  },
  {
    title: 'Predicting Facebook Group Relationship',
    authors: 'Rani P., Bhatia M.P.S., Tayal D.K.',
    venue: 'Int. J. of Innovative Technology and Exploring Engineering (IJITEE)',
    year: 2019,
    doi: '10.35940/ijitee.K1804.0981119',
    impact: 'Scopus',
    tags: ['Facebook', 'Prediction', 'Social Networks'],
    type: 'journal',
  },
  {
    title: 'SNA using User Experience',
    authors: 'Rani P., Tayal D.K., Bhatia M.P.S.',
    venue: 'IEEE Int. Conference on Machine Learning, Big Data, Cloud and Parallel Computing (COMITCon)',
    year: 2019,
    doi: '',
    impact: 'IEEE',
    tags: ['SNA', 'User Experience', 'Machine Learning'],
    citations: 6,
    type: 'conference',
  },
  {
    title: 'Designing a Project Leader Recommender System using Twitter Feed Analysis',
    authors: 'Rani P., Shokeen J.',
    venue: 'IEEE COMITCon 2019',
    year: 2019,
    doi: '10.1109/COMITCon.2019.8862261',
    impact: 'IEEE',
    tags: ['Recommender System', 'Twitter', 'NLP'],
    citations: 4,
    type: 'conference',
  },
  {
    title: 'A Comparative study of Qualitative and Quantitative SNA',
    authors: 'Rani P., Bhatia M.P.S., Tayal D.K.',
    venue: '6th Int. Conference on Computing for Sustainable Global Development, IEEE',
    year: 2019,
    doi: '',
    impact: 'IEEE',
    tags: ['SNA', 'Comparative Study', 'Analysis'],
    citations: 6,
    type: 'conference',
  },
  {
    title: 'Closeness Centrality using Communication aspect',
    authors: 'Rani P.',
    venue: '6th Int. Conference on Computing for Sustainable Global Development, IEEE',
    year: 2019,
    doi: '',
    impact: 'IEEE',
    tags: ['Centrality', 'Communication', 'SNA'],
    type: 'conference',
  },
  {
    title: 'An astute SNA with OWA Operator to Compare the Social Networks',
    authors: 'Rani P., Bhatia M.P.S., Tayal D.K.',
    venue: 'I.J. Information Technology and Computer Science',
    year: 2018,
    doi: '10.5815/ijitcs.2018.03.08',
    impact: 'Indexed',
    tags: ['SNA', 'OWA Operator', 'Comparison'],
    citations: 12,
    type: 'journal',
  },
  {
    title: 'Different Aspects, Challenges, and Impact of Social Networks with Mathematical Analysis of Teaching Learning',
    authors: 'Rani P., Tayal D.K., Bhatia M.P.S.',
    venue: 'JARDCS',
    year: 2018,
    doi: '',
    impact: 'Scopus',
    tags: ['Social Networks', 'Education', 'Analysis'],
    citations: 10,
    type: 'journal',
  },
  {
    title: 'A soft-computing based approach to Group relationship analysis using weighted arithmetic and geometric mean',
    authors: 'Rani P., Bhatia M.P.S., Tayal D.K.',
    venue: 'ICICC-2018, Springer',
    year: 2018,
    doi: '10.1007/978-981-13-2354-6_19',
    impact: 'Springer',
    tags: ['Soft Computing', 'Group Analysis', 'Social Networks'],
    citations: 8,
    type: 'conference',
  },
  {
    title: 'Qualitative SNA Methodology',
    authors: 'Rani P., Bhatia M.P.S., Tayal D.K.',
    venue: '5th Int. Conference on Computing for Sustainable Global Development, IEEE',
    year: 2018,
    doi: '',
    impact: 'IEEE',
    tags: ['SNA', 'Methodology', 'Qualitative'],
    citations: 7,
    type: 'conference',
  },
  {
    title: 'A Survey on Label Propagation based Techniques for Community Detection in Social Networks',
    authors: 'Rani P., Shokeen J.',
    venue: '5th Int. Conference on Computing for Sustainable Global Development',
    year: 2018,
    doi: '',
    impact: 'Conference',
    tags: ['Community Detection', 'Label Propagation', 'Survey'],
    type: 'conference',
  },
  {
    title: 'Recommendations Using Modified K-Means Clustering and Voting Theory',
    authors: 'Rani P., Shokeen J., Mullick D.',
    venue: 'Int. J. of Computer Science and Mobile Computing',
    year: 2017,
    doi: '',
    impact: 'Indexed',
    tags: ['Recommendations', 'K-Means', 'Voting'],
    citations: 4,
    type: 'journal',
  },
  {
    title: 'Social Recommender System Using Skyline Query and Reciprocal Scoring Technique',
    authors: 'Rani P., Gupta A.K.',
    venue: 'IOSR Journal of Engineering',
    year: 2017,
    doi: '',
    impact: 'Indexed',
    tags: ['Recommender System', 'Skyline Query', 'Social'],
    type: 'journal',
  },
  {
    title: 'Issues and Challenges in Link Prediction for Social Networks',
    authors: 'Rani P., Shokeen J.',
    venue: '11th INDIACom Conference',
    year: 2017,
    doi: '',
    impact: 'Conference',
    tags: ['Link Prediction', 'Social Networks', 'Challenges'],
    type: 'conference',
  },
]
